# Generated by Django 3.0.8 on 2020-07-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=60)),
                ('course_code', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('participants', models.CharField(max_length=20)),
                ('course_summary', models.CharField(max_length=250)),
                ('course_type', models.CharField(max_length=25)),
                ('maximum_participant', models.CharField(max_length=5)),
            ],
        ),
    ]
