# Generated by Django 3.0.8 on 2020-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200717_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Blood_Group', models.CharField(max_length=2)),
                ('Nationality', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Religion', models.CharField(max_length=25)),
                ('Phone_No', models.CharField(max_length=12)),
            ],
        ),
    ]
